name: GitHub Snake Game

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: # trigger
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Update v4

      - name: Generate GitHub Contributions Snake Animations
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=#216FEB
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#216FEB
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify dist directory
        run: |
          if [ ! -d "./dist" ]; then
            echo "Error: ./dist directory does not exist"
            exit 1
          fi
          ls -la ./dist

      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v4 # Update v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update snake animation üêç"
          force_orphan: true